theme = "term16_dark"

[editor]
true-color = true
line-number = "relative"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
y = ["yank_main_selection_to_clipboard"]
p = ["paste_clipboard_after"]
P = ["paste_clipboard_before"]
R = ["delete_selection", "paste_clipboard_before"]
C-r = ":reload-all"
"A-q" = ["move_char_right", "move_prev_word_end", "move_next_word_start", "delete_selection"]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
"A-q" = ["normal_mode", "move_char_right", "move_prev_word_end", "move_next_word_start", "delete_selection", "insert_mode"]

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
y = ["yank_main_selection_to_clipboard"]

[editor.file-picker]
hidden = false      # 开启：这样你能看到 .github, .config, .zshrc 等文件
git-ignore = true   # 保持开启：这样 Helix 依然会帮你过滤掉 Java 的 target/ 和 .git/ 目录

[editor.soft-wrap]
enable = true  # 1. 这里设置为 true，让它默认就是打开的

[keys.normal.space]
w = ":toggle soft-wrap.enable"
